"""Add NEXUS Agent Fabric

Revision ID: 3296f0eedc2b
Revises: 0cc9f59140aa
Create Date: 2026-09-04 13:12:06.462735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3296f0eedc2b'
down_revision: Union[str, Sequence[str], None] = '0cc9f59140aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nexus_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nexus_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_task_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nexus_tasks')
    op.drop_table('nexus_agents')
    # ### end Alembic commands ###
