"""Add FORGE Scientific Engine

Revision ID: 5004b6dd86c9
Revises: 3296f0eedc2b
Create Date: 2026-09-04 13:25:44.451625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5004b6dd86c9'
down_revision: Union[str, Sequence[str], None] = '3296f0eedc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forge_experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('experiment_design', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('evaluation_score', sa.Float(), nullable=True),
    sa.Column('nexus_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forge_experiments')
    # ### end Alembic commands ###
