"""Add ASCEND Long-Horizon Planner

Revision ID: 8361020f742c
Revises: 990f2b5dde40
Create Date: 2026-09-04 13:30:53.645784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8361020f742c'
down_revision: Union[str, Sequence[str], None] = '990f2b5dde40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascend_constraints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('objective_id', sa.String(), nullable=False),
    sa.Column('constraint_type', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ascend_milestones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('objective_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ascend_objectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ascend_objectives')
    op.drop_table('ascend_milestones')
    op.drop_table('ascend_constraints')
    # ### end Alembic commands ###
