"""Add MIRROR Simulation Engine

Revision ID: 990f2b5dde40
Revises: 5004b6dd86c9
Create Date: 2026-09-04 13:29:22.562393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990f2b5dde40'
down_revision: Union[str, Sequence[str], None] = '5004b6dd86c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirror_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirror_simulations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('base_state_snapshot', sa.Text(), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=True),
    sa.Column('time_scale', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mirror_simulations')
    op.drop_table('mirror_events')
    # ### end Alembic commands ###
