#!/usr/bin/env python3
"""Regenerate the ORION Obsidian vault from live repo state.

RULE (see AGENTS.md): run this before/with every commit so the vault always
reflects reality. It is also wired as a pre-commit hook (scripts/hooks/).

What it updates:
  - vault/01 - Project/ORION Capabilities.md        (owned file)
  - vault/01 - Project/ORION Screen-Vision & Actions.md (owned file)
  - vault/11 - Experiments/ORION Training Ledger.md (owned file, from
    logs/training_runs.jsonl)
  - vault/02 - Architecture/Repo Graph (graft).md   (owned file, from graft/)
  - vault/02 - Architecture/Repo Graph scope - *.md (owned files, one per scope)
  - vault/11 - Experiments/Knowledge Graph (graphify).md (owned file, from
    graphify-out/)
  - Marker-guarded blocks in:
      vault/01 - Project/ORION.md
      vault/00 - Home.md
      vault/00 - Knowledge Graph.md

Marker protocol: content between
    <!-- VAULT:AUTO:START note=<id> --> ... <!-- VAULT:AUTO:END -->
is regenerated on every run; anything outside markers is left untouched.

The graph notes come from scripts/vault/export_graft.py (see
docs/plans/graft-graphify-vault-merge.md). If that module or its inputs are
missing, the rest of the vault still builds - the graph notes are skipped with
a warning rather than failing the pre-commit hook.

    python scripts/vault/build_vault.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

REPO_ROOT = Path(__file__).resolve().parents[2]
VAULT = REPO_ROOT / "vault"
LEDGER = REPO_ROOT / "logs" / "training_runs.jsonl"

START = "<!-- VAULT:AUTO:START note={note} -->"
END = "<!-- VAULT:AUTO:END -->"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="minutes")


def git_log(n: int = 5) -> list[str]:
    try:
        out = subprocess.run(
            ["git", "log", f"-{n}", "--oneline"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return [ln for ln in out.stdout.splitlines() if ln.strip()]
    except Exception:  # noqa: BLE001 - fall back silently
        return []


def load_ledger() -> list[dict]:
    if not LEDGER.exists():
        return []
    rows = []
    for line in LEDGER.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return rows


ISO_TS_RE = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?:[+-]\d{2}:\d{2})?")


def reuse_existing_stamp(prev: str, content: str, ts: str | None) -> str:
    """Rewrite `content`'s fresh sync stamp to the one already in `prev`.

    The builder stamps every note with the current minute. Without this, a run
    that changed *nothing* would still rewrite all 19 notes, and the pre-commit
    hook would report a diff (and churn the index) on every commit. With it, the
    stamp only advances when some other part of the note actually moved - which
    is what makes a second consecutive run print "no changes (already current)".
    """
    if not ts:
        return content
    m = ISO_TS_RE.search(prev)
    if not m or m.group(0) == ts:
        return content
    return content.replace(ts, m.group(0))


def write_owned(path: Path, content: str, ts: str | None = None) -> bool:
    """Overwrite a builder-owned note; returns True if changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    prev = path.read_text(encoding="utf-8") if path.exists() else ""
    if prev:
        content = reuse_existing_stamp(prev, content, ts)
    if prev == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def upsert_marker(path: Path, note: str, block: str, ts: str | None = None) -> bool:
    """Insert/replace a marker block in an existing note; returns True if changed."""
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    start = START.format(note=note)
    end = END
    rendered = f"{start}\n{block}\n{end}"
    if start in text:
        pre, _rest = text.split(start, 1)
        if end in _rest:
            post = _rest.split(end, 1)[1]
            new_text = pre + rendered + post
        else:  # broken marker: append end at file tail
            new_text = pre + rendered
    else:
        # insert before the final horizontal rule (or append)
        new_text = text.rstrip()
        new_text += f"\n\n---\n\n{rendered}\n"
    new_text = reuse_existing_stamp(text, new_text, ts)
    if new_text == text:
        return False
    path.write_text(new_text, encoding="utf-8")
    return True


# ---------------------------------------------------------------- content


def capabilities_note(ts: str) -> str:
    return f"""# ORION Capabilities

#project #experiment

> *Auto-generated by `scripts/vault/build_vault.py` — edit the builder, not this file.*
> *Last sync: {ts}*

ORION's capabilities are honest bridges: a tiny vision model captions pixels, a
whitelist executes screen actions, edge-tts speaks. Training metrics live in
[[ORION Training Ledger]]; project root is [[ORION]].

## Capability Matrix (verified state)

| Capability | Status | Bridge | Evidence |
|---|---|---|---|
| Screen vision (see) | **VERIFIED** | Florence-2 caption of `ImageGrab` capture | live desktop captioned |
| Screen actions (do) | **VERIFIED** (whitelist) | `os.startfile` + optional pyautogui | confirmed `open notepad` launched + re-captured |
| Image captioning | **VERIFIED** | Florence-2-base (~0.23B, CPU) | probe caption produced |
| Image generation | **VERIFIED** | segmind/tiny-sd, 8 steps 512² | structural PNG check |
| Voice / TTS | **VERIFIED** | edge-tts + SAPI fallback | audio artifact written |
| Low-memory inference | **VERIFIED** (0.5B) | airllm 4.0.0 bridge | 16 tokens / 108.5 s, RSS flat 386 MB |
| Big-teacher inference | **BLOCKED** | airllm 7B | needs ~15.2 GB disk (have ~9 GB) |
| Context extension | mechanics VERIFIED / retrieval **UNPROVEN** | YaRN scale 8 × LoRA | 2K/4K probes run; retrieval all False |
| Instruction following | **UNPROVEN** | 100M SFT | outputs stay filler-grade |

> Honesty rule: VERIFIED = reproduced here; UNPROVEN = not demonstrated; BLOCKED = missing hardware/disk.

## How the pieces connect

- [[ORION Screen-Vision & Actions]] — the "see your screen and do things" layer
- [[ORION Training Ledger]] — every training number, nothing spun
- [[AURA Intelligence]] — the architectural multimodal-intelligence target
- Source of truth for reproduction: `docs/ORION_CAPABILITIES.md` (repo)

## Backlinks / Related

- [[00 - Home]]
- [[ORION]]
- [[00 - Knowledge Graph]]
"""


def screen_note(ts: str) -> str:
    return f"""# ORION Screen-Vision & Actions

#project #experiment

> *Auto-generated by `scripts/vault/build_vault.py` — edit the builder, not this file.*
> *Last sync: {ts}*

"ORION can see your screen and do things" — the honest design: pixels never
reach the model. A screenshot is captioned by Florence-2 and ORION works from
the *description*; actions are whitelist-only and confirm-first.

## See

- `orion_runner/screen.py` → `see()`; CLI `scripts/orion_see.py`
- **VERIFIED:** live 1920×1080 capture captioned (e.g. *"a screenshot of a
  computer screen with a code on it"*); shots in `data/screenshots/`

## Act

- `orion_runner/actions.py` (whitelist, confirm-first) + `scripts/orion_act.py`
- Verbs: `open` (os.startfile, zero deps), `type` / `key` / `click` (need pyautogui)
- **VERIFIED:** confirmed `open notepad` launched → screen re-captured + re-described
- Audit trail: `logs/orion_actions.jsonl` (confirmed / aborted / error)

## Assistant integration

- `scripts/orion_assistant.py` routes plain words → whitelisted verbs
- Non-screen asks get an honest "not wired yet" — no fake free-form reasoning

## Training status (caption → action mapping)

- **Honest negative so far:** two formats, both 0/10 held-out verb accuracy —
  see [[ORION Training Ledger]] runs `teach-distill-b63388c3` and
  `teach-distill-f8590729`. Not a working auto-pilot; the user picks the action.

## Related

- [[ORION Capabilities]]
- [[ORION Training Ledger]]
- [[ORION]]
- [[AURA Intelligence]]
"""


def ledger_note(ts: str, rows: list[dict], commits: list[str]) -> str:
    if not rows:
        runs_table = "_(no runs recorded yet — `logs/training_runs.jsonl` empty)_"
    else:
        lines = [
            "| run_id | status | dataset | rows | epochs | start→end | Δ% | eval | dur(s) |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for r in rows:
            rid = r.get("run_id", "?")
            status = r.get("status", "?")
            ds = Path(str(r.get("dataset_path", "?"))).name
            n = r.get("num_samples", "-")
            ep = r.get("epochs", "-")
            sl = r.get("starting_loss")
            el = r.get("ending_loss")
            red = r.get("loss_reduction_pct")
            ev = r.get("eval_loss")
            dur = r.get("duration_seconds")
            fmt = lambda v: f"{v:.4f}" if isinstance(v, (int, float)) else "-"
            lines.append(
                f"| `{rid}` | {status} | {ds} | {n} | {ep} | "
                f"{fmt(sl)} → {fmt(el)} | {red if isinstance(red, (int, float)) else '-'} | "
                f"{fmt(ev)} | {dur if isinstance(dur, (int, float)) else '-'} |"
            )
        runs_table = "\n".join(lines)

    commit_lines = "\n".join(f"- `{c}`" for c in commits) or "- _(git unavailable)_"

    return f"""# ORION Training Ledger

#experiment #governance

> *Auto-generated by `scripts/vault/build_vault.py` from
> `logs/training_runs.jsonl` — edit the builder, not this file.*
> *Last sync: {ts}*

Every training run ORION logged, with honest metrics. Failures are recorded
with `error_message`. Run → capability links: [[ORION Capabilities]] and
[[ORION Screen-Vision & Actions]].

## Runs

{runs_table}

## Honest warnings

- Loss gains are training-metric gains; generation quality remains
  filler-grade at the 100M scale (**UNPROVEN**).
- Vision-action runs converge on loss yet score **0/10 held-out** — see
  [[ORION Screen-Vision & Actions]].

## Recent commits (context)

{commit_lines}

## Related

- [[ORION]]
- [[ORION Capabilities]]
- [[00 - Knowledge Graph]]
- [[00 - Home]]
"""


def orion_block(ts: str, commits: list[str]) -> str:
    commit_lines = "\n".join(f"- `{c}`" for c in commits) or "- _(git unavailable)_"
    return f"""## Autonomously Trained Capabilities — auto

> Last sync: {ts} · source: `scripts/vault/build_vault.py` · full truth in
> [[ORION Capabilities]], [[ORION Screen-Vision & Actions]], [[ORION Training Ledger]]

- [[ORION Capabilities]] — verified capability matrix (screen vision, TTS, image gen, airllm, context)
- [[ORION Screen-Vision & Actions]] — see-your-screen + confirm-first actions
- [[ORION Training Ledger]] — every run, every number
- [[Repo Graph (graft)]] — the repo as a queryable call graph, one note per scope
- [[Knowledge Graph (graphify)]] — the community graph, scope- and date-labelled

Recent commits:

{commit_lines}"""


def home_block(ts: str) -> str:
    return f"""### ORION Model & Training (auto)

> Last sync: {ts}

- [[ORION Capabilities]] — capability matrix with verified/unproven labels
- [[ORION Training Ledger]] — every training run, honest numbers
- [[ORION Screen-Vision & Actions]] — see your screen, act with confirmation

### Repo & Knowledge Graphs (auto)

> Last sync: {ts} · built from `graft/` and `graphify-out/` by
> `scripts/vault/export_graft.py`

- [[Repo Graph (graft)]] — what calls what: one note per top-level scope
- [[Knowledge Graph (graphify)]] — what clusters together: communities + god
  nodes, labelled with its own scope and date so it is never mistaken for live"""


def kg_block(ts: str) -> str:
    return f"""## ORION Capability + Graph Nodes (auto)

> Last sync: {ts}

### Capability edges

- `ORION Capabilities` → `ORION Training Ledger` : every verified run/claim
- `ORION Screen-Vision & Actions` → `ORION Capabilities` : the see/act layer is a verified capability
- `ORION Capabilities` → `Forensic Audit` : same provenance discipline, model-scale

### Graph edges (repo graph → community graph)

- `ORION` → `Repo Graph (graft)` : the repo as a queryable call graph, one note per scope
- `Repo Graph (graft)` → `Knowledge Graph (graphify)` : same repo, different question
  (who calls whom vs. what clusters together); the community graph is scoped to
  `scripts/training` and dated in its own note
- `Repo Graph (graft)` → `ORION Screen-Vision & Actions` : the `orion_runner` scope is what see/do actually is

### Two graphs, honestly scoped

- **Repo Graph (graft)** — VERIFIED current: rebuilt from the live `graft/`
  tree on every run. Edges stay in graft's `.graph` DB (`graft callers <sym>`);
  Obsidian holds the nodes, not the edges.
- **Knowledge Graph (graphify)** — VERIFIED as a *labelled snapshot*, not a live
  graph: `graphify-out/` is only re-run deliberately, so its note carries its own
  scope + date and is never presented as current.

Edges as wikilinks: [[ORION Capabilities]], [[ORION Screen-Vision & Actions]],
  [[ORION Training Ledger]], [[Repo Graph (graft)]], [[Knowledge Graph (graphify)]]"""


# ---------------------------------------------------------------- main


def graph_notes() -> dict[Path, str]:
    """Notes from scripts/vault/export_graft.py (graft + graphify projections).

    Never raises: a broken/missing exporter or a missing graft/ tree degrades to
    an empty dict plus a warning, so the pre-commit hook cannot be wedged.
    """
    try:
        import export_graft  # noqa: PLC0415 - sibling module, path set above

        return export_graft.build_notes()
    except Exception as exc:  # noqa: BLE001 - vault must still build
        print(f"[VAULT] WARN: graph notes skipped ({type(exc).__name__}: {exc})")
        return {}


def main() -> int:
    ts = now_iso()
    rows = load_ledger()
    commits = git_log(6)
    changed: list[str] = []

    notes = {
        VAULT / "01 - Project" / "ORION Capabilities.md": capabilities_note(ts),
        VAULT / "01 - Project" / "ORION Screen-Vision & Actions.md": screen_note(ts),
        VAULT / "11 - Experiments" / "ORION Training Ledger.md": ledger_note(
            ts, rows, commits
        ),
    }
    notes.update(graph_notes())
    for path, content in sorted(notes.items()):
        if write_owned(path, content, ts):
            changed.append(str(path.relative_to(REPO_ROOT)))

    marks = [
        (
            VAULT / "01 - Project" / "ORION.md",
            "orion-current",
            orion_block(ts, commits),
        ),
        (VAULT / "00 - Home.md", "home-training", home_block(ts)),
        (VAULT / "00 - Knowledge Graph.md", "kg-orion", kg_block(ts)),
    ]
    for path, note, block in marks:
        if upsert_marker(path, note, block, ts):
            changed.append(str(path.relative_to(REPO_ROOT)))

    if changed:
        print("[VAULT] updated:")
        for c in changed:
            print(f"  + {c}")
    else:
        print("[VAULT] no changes (already current)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
